### ISSUE TITLE
poor performance after implementation `deep relations`

### ISSUE THREAD

**Issue by Edsol** [drizzle-team/drizzle-graphql#11]
I am using the extension on some example databases (mysql and postgres) to develop my [extension](https://github.com/Edsol/drizzle-schema-generator).

I have big memory problems on version 0.7.x of the extension

Large MySql database info (via Apollo):
<img width="341" alt="mysql large db" src="https://github.com/drizzle-team/drizzle-graphql/assets/19670024/dab18407-a733-46f3-ba3c-3301e414b201">

Small MySql database info (via Apollo):
<img width="329" alt="mysql small db" src="https://github.com/drizzle-team/drizzle-graphql/assets/19670024/aea2d1c2-c5be-4fa9-93a9-d540f3a6184d">

Large Postgres database info (via Apollo):
<img width="336" alt="postgres larege db" src="https://github.com/drizzle-team/drizzle-graphql/assets/19670024/98e453b2-9443-4ed8-8840-27fe075d33d2">

Small Postgres database info (via Apollo):
<img width="337" alt="postgres small db" src="https://github.com/drizzle-team/drizzle-graphql/assets/19670024/ad9175c1-1ddd-405d-a283-5ffb2a08a14d">

version 0.6.0

memory used:
- small mysql schema: about 120MB RAM
- mysql schema large: about 900MB RAM

- small postgres schema: about 100MB RAM
- large postgres schema: about 2.50GB of RAM

version 0.7.2

memory used:
- mysql schema small: about 110MB RAM
- mysql schema large (without relationships): about 700MB RAM
- mysql schema large: over 20GB RAM (without finishing processing)

- small postgres schema: about 100MB RAM
- large postgres schema (without relationships): over 1.70GB RAM
- large postgres schema: over 20GB RAM (without finishing processing)

**Comment by Sukairo-02** [comment]
I'll see what I can do about that, but since I'm already caching and reusing whatever is possible, it might be the case that there's nothing left to improve

**Comment by Edsol** [comment]
to limit the load, could a configuration parameter to exclude or limit the depth of relationships be a temporary solution?

**Comment by Sukairo-02** [comment]
Yes, that's possible for the runtime
No idea how to implement the types for that case though

**Comment by Sukairo-02** [comment]
Actually, I might be able to optimize something here. Just noticed an awfully big amount of inputs, I should be able to reduce that,  expect a patch soon.

**Comment by Sukairo-02** [comment]
I've added depth limiter for now, hopefully I'll be able to do something about it in the future.

**Comment by Edsol** [comment]
the depth limit works, it may be the right compromise on rather large databases with many relationships.

Thanks

**Comment by anthonyhoegberg** [comment]
> I've added depth limiter for now, hopefully I'll be able to do something about it in the future.

Is it possible to configure the depth?
