### ISSUE TITLE
Drizzle add relational objects during insert/update?

### ISSUE THREAD

**Issue by anthonyhoegberg** [drizzle-team/drizzle-graphql#3]
Is it possible to get relations in the mutations (insert/update) as well, like lets say we have a user and a post table currently when i do a query i can request the posts as well however i would also like to be able to add posts during the creation of the user object.

when i create a user, i would like to also add posts as a subfield in the generated UserInsertInput type so when i create the user object, i can attach posts to it instead of doing 2 different inserts.

This might not be a good example with user and post, but i have other data where this would be the easiest way to insert a lot of data at once, and i have many different relations aswell

**Comment by Sukairo-02** [comment]
I'll check if and how that's possible to implement, would likely need Drizzle RQB to support such actions to begin with.

**Comment by anthonyhoegberg** [comment]
Thank you for your quick response

**Comment by Sukairo-02** [comment]
It's not something I can implement without Drizzle doing it first in the RQB, so until then this issue is on hold.
