### ISSUE TITLE
Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by shashkovdanil** [drizzle-team/drizzle-graphql#5]
I have error here https://github.com/drizzle-team/drizzle-graphql/blob/cb8711111c422c21e02fddd88c7aabe2ef0810ce/src/util/builders/pg.ts#L367

Setup db code: https://github.com/shashkovdanil/ai-plate-landing/blob/main/src/services/db/connection.ts
Schema: https://github.com/shashkovdanil/ai-plate-landing/blob/main/src/schema.ts

**Comment by Sukairo-02** [comment]
That's because you've passed incomplete schema into drizzle constructor. I've already submitted [pull request](https://github.com/shashkovdanil/ai-plate-landing/pull/1) that fixes it to that repo a few days ago.
