### ISSUE TITLE
 "Cannot convert undefined or null to object" using nextjs + apollo client with autogenerated mutations

### ISSUE THREAD

**Issue by ybtam** [drizzle-team/drizzle-graphql#6]
Tech: 
- nextjs + apollo client
- graphql yoga + drizzle-graphql

Issue:
- When using the autogenerated mutations with the frontend i get "Cannot convert undefined or null to object". It also does not alter the data in DB. When testing the mutation in GraphiQL or Postman everything works just fine.
- When using custom mutation, everything is fine.

Expect:
Mutation to execute and return the fields.

Simplified copy of the code:
https://github.com/ybtam/drizzle-graphql-bug

**Comment by Sukairo-02** [comment]
Found the issue, expect a fix soon.

**Comment by Sukairo-02** [comment]
`0.3.6` fixes it, thanks for submitting the issue.
