### ISSUE TITLE
Generate GraphQL Enum type

### ISSUE THREAD

**Issue by ybtam** [drizzle-team/drizzle-graphql#7]
Would it be possible to generate enum types from schema definitions?

`pgEnum('type', ['date', 'email', 'url', 'number', 'text']);`

into 

`enum type {
  date
  email
  url
  number
  text
}`

**Comment by Sukairo-02** [comment]
That should be possible, I'll look into it.

**Comment by Sukairo-02** [comment]
Already implemented locally, expect an update very soon.

**Comment by Sukairo-02** [comment]
`v0.4.0` - added enum support.
